In [1]:
import pandas as pd 
import numpy as np

In [10]:
df = pd.read_excel(r'Downloads/chatgpt1.xlsx')
print(df)

                        Datetime             Tweet Id  \
0      2023-01-22 13:44:34+00:00  1617156270871689984   
1      2023-01-22 13:44:39+00:00  1617156291046129920   
2      2023-01-22 13:44:44+00:00  1617156308926340096   
3      2023-01-22 13:44:49+00:00  1617156332297250048   
4      2023-01-22 13:44:52+00:00  1617156345064570112   
...                          ...                  ...   
49996  2023-01-24 06:57:56+00:00  1617778712082089984   
49997  2023-01-24 06:57:59+00:00  1617778726393240064   
49998  2023-01-24 06:58:00+00:00  1617778728481989888   
49999  2023-01-24 06:58:01+00:00  1617778731678040064   
50000  2023-01-24 06:58:01+00:00  1617778733355790080   

                                                    Text         Username  \
0      ChatGPTで遊ぶの忘れてた！！\n書類ä...      mochico0123   
1      @AlexandrovnaIng Prohibition of ChatGPT has be...  Caput_LupinumSG   
2      Schaut Euch an, was @fobizz @DianaKnodel alles...            ciffi   
3      

In [3]:

#Creating a function that takes care of all the preprocessing stuff.
def preprocess():

  df['Text'] = df['Text'].str.lower() # Ensuring all words in the Tweet column of training data are lowercased

  # Parsing the stop_words.txt file and storing all the words in a list.
  stopwords = []
  with open('chatgpt1.xlsx','r') as file:    
      for line in file:         
          for word in line.split():            
              stopwords.append(word)

  # Removing all stopwords from all the tweets in training data.
  df["Text"] = trained["Text"].apply(lambda func: ' '.join(sw 
                                            for sw in func.split() 
                                            if sw not in stopwords))
    
  #Training Data
  df['Text'] = df['Text'].str.replace(r'http?://[^\s<>"]+|www\.[^\s<>"]+', '') # Removing hyperlinks from all the tweets
  df['Text'] = df['Text'].str.replace('@[A-Za-z0-9]+', '') # Removing usernames from all the tweets.
  df['Text'] = df['Text'].str.replace(r'\B#\w*[a-zA-Z]+\w*', '') # Removing hashtags, including the text, from all the tweets
  df['Text'] = df['Text'].str.replace('\d+', '') # Removing numbers from all the tweets


  special_chars = ["!",'"',"%","&","amp","'","(",")", "*","+",",","-",".",
                  "/",":",";","<","=",">","?","[","\\","]","^","_",
                  "`","{","|","}","~","–","@","#","$"]

  for c in special_chars:
      df['Text'] = df['Text'].str.replace(c,'') # Removing all special characters from all the tweets

In [4]:
df.head(30)

Datetime             Tweet Id  \
0   2023-01-22 13:44:34+00:00  1617156270871689984   
1   2023-01-22 13:44:39+00:00  1617156291046129920   
2   2023-01-22 13:44:44+00:00  1617156308926340096   
3   2023-01-22 13:44:49+00:00  1617156332297250048   
4   2023-01-22 13:44:52+00:00  1617156345064570112   
5   2023-01-22 13:45:00+00:00  1617156376983200000   
6   2023-01-22 13:45:03+00:00  1617156389217890048   
7   2023-01-22 13:45:04+00:00  1617156393898739968   
8   2023-01-22 13:45:06+00:00  1617156404137289984   
9   2023-01-22 13:45:07+00:00  1617156405869370112   
10  2023-01-22 13:45:07+00:00  1617156409254370048   
11  2023-01-22 13:45:08+00:00  1617156410634010112   
12  2023-01-22 13:45:10+00:00  1617156421719830016   
13  2023-01-22 13:45:12+00:00  1617156430183770112   
14  2023-01-22 13:45:14+00:00  1617156438706550016   
15  2023-01-22 13:45:15+00:00  1617156441420270080   
16  2023-01-22 13:45:18+00:00  1617156454141530112   
17  2023-01-22 13:45:22+00:00  1617156468951729920   
18  2023-01-22 13:45:26+00:00  1617156485846360064   
19  2023-01-22 13:45:32+00:00  1617156511733779968   
20  2023-01-22 13:45:32+00:00  1617156513642030080   
21  2023-01-22 13:45:38+00:00  1617156539097260032   
22  2023-01-22 13:45:46+00:00  1617156570806370048   
23  2023-01-22 13:45:54+00:00  1617156606453580032   
24  2023-01-22 13:45:57+00:00  1617156616666729984   
25  2023-01-22 13:45:59+00:00  1617156625256640000   
26  2023-01-22 13:46:02+00:00  1617156636656940032   
27  2023-01-22 13:46:02+00:00  1617156638120570112   
28  2023-01-22 13:46:04+00:00  1617156647855739904   
29  2023-01-22 13:46:14+00:00  1617156687202490112   

                                                 Text         Username  \
0   ChatGPTで遊ぶの忘れてた！！\n書類ä...      mochico0123   
1   @AlexandrovnaIng Prohibition of ChatGPT has be...  Caput_LupinumSG   
2   Schaut Euch an, was @fobizz @DianaKnodel alles...            ciffi   
3   Bow down to chatGPT 🫡..... https://t.co/ENT...    Vishwasrisiri   
4   Profilinde vatan, Türkiye falan yazan bireyle...   0xGenetikciniz   
5   ChatGPT’nin bilinmeyen arka planı: Ucuz iş...    GazeteKarinca   
6   ChatGPT runs 10K Nvidia training GPUs with pot...   FierceElectron   
7   @SWENGDAD There is repetitive work in every jo...       xlr8harder   
8   I created a fictional jewelry brand using Chat...      Kosuke_dazo   
9   It will look similar to irobot. The company wi...      EricRIngram   
10  If you ever played a game like assassin’s cr...        isree1998   
11  AI will initiate a new era of entrepreneurship...         IsEgaley   
12  最新コメント15件（01/22 22:45）\n\nã€...    nowtice_news2   
13  Są dobre i złe wieści na temat ChatGPT.\n\n...           uwteam   
14  #ChatGPT wydaje na operacjÄ™ w chmurze 3 mln d...  PetrosTovmasyan   
15  🤯 #ChatGPT writes excel formulas!\n\n#Micro...   JakeMillerTech   
16  J'ai juste demander à l'IA chatGPT de faire u...          Veskii_   
17  Google Presenta Sparrow, Su Inteligencia Artif...        varelapma   
18  Pay $42 per month or start using your brain ag...     5mintalkaysh   
19  Your own AI knowledge base chatbot with OpenAI...   M157q_News_RSS   
20  ChatGPT | write me an article about Emanuele B...  emanuelebertoli   
21  @Slipcatch @nickhedley #ChatGPT ain’t got no...       WesHellyar   
22  @paulgp Leverage ChatGPT…you will be surpris...  ACAPITALGROUP17   
23  @FrankDeya The anxiety I get when I want to us...    JoycemwangiKE   
24  esse chatGPT é bonzão pra explicar código, ...          joasnog   
25                                     chatgpt ☺️       lemanbrick   
26  ແຕ່ກີ້ຄົນຫາເງິນà...        xokthilat   
27        #Tech: Google is freaking out about ChatGPT         FamsMert   
28  Derrière le #succès de #ChatGPT, #OpenAI a u...     SkySpace1865   
29  There goes the entire #PR industry.  I just wr...        matwilcox   

                                            Permali

In [6]:
# shape of dataframe
df.shape

(50001, 20)

In [7]:
df.isnull().sum()

Datetime              0
Tweet Id              0
Text                  5
Username              0
Permalink             0
User                  0
Outlinks          30059
CountLinks        30059
ReplyCount            0
RetweetCount          0
LikeCount             0
QuoteCount            0
ConversationId        0
Language              0
Source                0
Media             40499
QuotedTweet       46438
MentionedUsers    32832
hashtag               0
hastag_counts         0
dtype: int64

No of training examples: 40001
No of testing examples: 10000 


In [8]:
y_col = 'Language'
y = df[y_col]

x_col = 'Text'
x = df [x_col]
y,x

(0        ja
 1        en
 2        de
 3        en
 4        tr
          ..
 49996    de
 49997    de
 49998    it
 49999    en
 50000    es
 Name: Language, Length: 50001, dtype: object,
 0        ChatGPTで遊ぶの忘れてた！！\n書類ä...
 1        @AlexandrovnaIng Prohibition of ChatGPT has be...
 2        Schaut Euch an, was @fobizz @DianaKnodel alles...
 3        Bow down to chatGPT 🫡..... https://t.co/ENT...
 4        Profilinde vatan, Türkiye falan yazan bireyle...
                                ...                        
 49996    #ChatGPT ist ein #Chatbot, der durch künstlic...
 49997    @r8r Ich hab mal die AI dazu befragt (ChatGPT)...
 49998    5 minuti di #chatGPT e ho capito che apprende ...
 49999    Portland Shop Uses ChatGPT To Tell Family Stor...
 50000    Ahora sueño con el día en que Amazon integre...
 Name: Text, Length: 50001, dtype: object)

In [9]:

training_data_x = x.sample(frac=0.8 , random_state=25)
training_data_x = x.drop(training_data_x.index)


testing_data_x = x.sample(frac=0.8 , random_state=25)
testing_data_x = x.drop(training_data_x.index)

print(f"No of training examples: {training_data.shape[0]}")
print(f"No of testing examples: {testing_data.shape[0]} ")

NameError: name 'training_data' is not defined

In [37]:

training_data_y = y.sample(frac=0.8 , random_state=25)
training_data_y = y.drop(training_data_x.index)


testing_data_y = y.sample(frac=0.8 , random_state=25)
testing_data_y = y.drop(training_data_x.index)

print(f"No of training examples: {training_data.shape[0]}")
print(f"No of testing examples: {testing_data.shape[0]} ")

No of training examples: 40001
No of testing examples: 10000 


In [38]:
def computeTF(wordDict , bagOfWords):
    tfDict ={}
    bagOfWordsCount = len(bagOfWords)
    for word , count in wordDict.items():
        tfDict[word] = count / float(bagOfWordsCount)
        return tfDict

In [39]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

# Handle missing values
training_data_x = np.where(pd.isnull(training_data_x), '', training_data_x)
testing_data_x = np.where(pd.isnull(testing_data_x), '', testing_data_x)

# create CountVectorizer object
count_vect = CountVectorizer()

# fit and transform the training data
X_train_counts = count_vect.fit_transform(training_data_x)

# transform the testing data
X_test_counts = count_vect.transform(testing_data_x)


In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer

# create TfidfVectorizer object
tfidf_vect = TfidfVectorizer()

# fit and transform the training data
X_train_tfidf = tfidf_vect.fit_transform(training_data_x)

# transform the testing data
X_test_tfidf = tfidf_vect.transform(testing_data_x)


In [41]:
# Display the vectorized data for training set
print("Training set - Vectorized data:")
print(X_train_counts.toarray())

# Display the vectorized data for testing set
print("Testing set - Vectorized data:")
print(X_test_counts.toarray())


Training set - Vectorized data:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Testing set - Vectorized data:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [44]:
print("Number of samples in X_train_counts:", X_train_counts.shape[0])
print("Number of labels in training_data_y:", len(training_data_y))


Number of samples in X_train_counts: 10000
Number of labels in training_data_y: 40001


In [46]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Initialize the Decision Tree classifier
decision_tree = DecisionTreeClassifier()

# Train the Decision Tree classifier
decision_tree.fit(X_train_counts, training_data_y[:X_train_counts.shape[0]])

# Predict on the testing set
decision_tree_preds = decision_tree.predict(X_test_counts)

# Calculate evaluation metrics
accuracy = accuracy_score(testing_data_y, decision_tree_preds)
precision = precision_score(testing_data_y, decision_tree_preds, average='macro')
recall = recall_score(testing_data_y, decision_tree_preds, average='macro')
f1 = f1_score(testing_data_y, decision_tree_preds, average='macro')

# Print the evaluation metrics
print("Decision Tree - Accuracy: {:.4f}, Precision: {:.4f}, Recall: {:.4f}, F1 Score: {:.4f}"
      .format(accuracy, precision, recall, f1))


/Users/student/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Decision Tree - Accuracy: 0.5232, Precision: 0.0182, Recall: 0.0174, F1 Score: 0.0169


In [4]:
import pandas as pd

# Load your DataFrame from the Excel file
df = pd.read_excel('chatgpt1.xlsx')

# Handle NaN values in the 'Text' column
df['Text'].fillna('', inplace=True)

# Convert text data into numerical features using TF-IDF vectorization
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['Text'])

# Cluster the text data using KMeans algorithm
num_clusters = 5
kmeans = KMeans(n_clusters=num_clusters)
kmeans.fit(X)

# Perform further analysis or utilize the clustering results as needed
# ...


/Users/student/anaconda3/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


AttributeError: 'NoneType' object has no attribute 'split'

In [5]:
!pip install -U scikit-learn threadpoolctl


  Attempting uninstall: threadpoolctl
    Found existing installation: threadpoolctl 2.2.0
    Uninstalling threadpoolctl-2.2.0:
      Successfully uninstalled threadpoolctl-2.2.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
orange3 3.32.0 requires PyQt5!=5.15.1,>=5.12, which is not installed.
orange3 3.32.0 requires PyQtWebEngine>=5.12, which is not installed.


In [6]:
import pandas as pd

# Load your DataFrame from the Excel file
df = pd.read_excel('chatgpt1.xlsx')

# Handle NaN values in the 'Text' column
df['Text'].fillna('', inplace=True)

# Convert text data into numerical features using TF-IDF vectorization
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['Text'])

# Cluster the text data using KMeans algorithm
num_clusters = 5
kmeans = KMeans(n_clusters=num_clusters)
kmeans.fit(X)

# Perform further analysis or utilize the clustering results as needed
# ...


/Users/student/anaconda3/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


AttributeError: 'NoneType' object has no attribute 'split'